name: Keep Alive
on:
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут
  workflow_dispatch:  # Ручной запуск
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://Y7-Shtnk52.onrender.com)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "❌ Ошибка: сервер вернул $RESPONSE"
            exit 1
          else
            echo "✅ Сервер активен (HTTP $RESPONSE)"
          fi
